pub(crate) const POSITION_NAMES: [&str; 15] = [
    "GK", "SW", "DL", "DC", "DR", "DM", "ML", "MC", "MR", "AML", "AMC", "AMR", "ST", "WBL", "WBR",
];

pub(crate) const PLAYER_ATTRIBUTE_NAMES: [&str; 54] = [
    "Crossing",
    "Dribbling",
    "Finishing",
    "Heading",
    "Long Shots",
    "Marking",
    "Off the Ball",
    "Passing",
    "Penalty Taking",
    "Tackling",
    "Vision",
    "Handling",
    "Aerial Reach",
    "Command of Area",
    "Communication",
    "Kicking",
    "Throwing",
    "Anticipation",
    "Decisions",
    "One on Ones",
    "Positioning",
    "Reflexes",
    "First Touch",
    "Technique",
    "Left Foot",
    "Right Foot",
    "Flair",
    "Corners",
    "Teamwork",
    "Work Rate",
    "Long Throws",
    "Eccentricity",
    "Rushing Out",
    "Punching",
    "Acceleration",
    "Free Kick Taking",
    "Strength",
    "Stamina",
    "Pace",
    "Jumping Reach",
    "Leadership",
    "Dirtiness",
    "Balance",
    "Bravery",
    "Consistency",
    "Aggression",
    "Agility",
    "Important Matches",
    "Injury Proneness",
    "Versatility",
    "Natural Fitness",
    "Determination",
    "Composure",
    "Concentration",
];

pub(crate) const HIDDEN_ATTRIBUTE_INDEXES: [usize; 5] = [41, 44, 47, 48, 49];

#[derive(Clone, Copy)]
pub(crate) struct FmDate {
    pub(crate) year: u16,
    pub(crate) day_of_year: u16,
}
